### PR TITLE
Add presentationConfig block to PresentModallyAction

### PR DESCRIPTION
**Pull request by vykut**
Hi, 

Currently `ViewControllerActions.PresentModallyAction` allows only for configuring the `UIPopoverPresentationController` instance. 
In our usecase, we need to configure the `UISheetPresentationController` which is only available in iOS 15 or later.
I have modified the existing `ViewControllerActions.PresentModallyAction` to allow for such configuration, by providing the generic `UIPresentationController` in a config block, which can then be casted to either `UISheetPresentationController`, or `UIPopoverController`.

Therefore, I generalized the API a bit, but have kept the existing functionality of configuring only the `UIPopoverPresentationController` so this change is not a breaking one for existing consumers.

### CODE REVIEW

**Comment by ekazaev** [comment]
Ho @vykut. Thank you very mich. yes sorry. I haven't recently updated the route-composer as my current app still supports ios 14 😂. Nice job.

**Comment by vykut** [comment]
@ekazaev are you going to tag a new release or should we point to the master branch?

**Comment by ekazaev** [comment]
@vykut of course. Just I am not by the laptop atm.

**Comment by ekazaev** [comment]
@vykut New version was released

**Pull request merged**
