### PR TITLE
make compatible to build for targets with app extensions

### PR DESCRIPTION
**Pull request by max-potapov**
reproduced with Xcode 13 beta 3

### CODE REVIEW

**Review by ekazaev — APPROVED** [review]

**Comment by ekazaev** [comment]
@max-potapov Does it need to be added anywhere else? I haven't tested it myself with app extensions 😱

**Comment by max-potapov** [comment]
> @max-potapov Does it need to be added anywhere else? I haven't tested it myself with app extensions 😱

So, my project is still failing, but this framework looks good now. Basically you can check by search `UIApplication.shared` calls which can't be called from app extensions code.

**Comment by max-potapov** [comment]
Unfortunately the work is not finished. I'm closing this for now and I'll re-open it when all work will be done

**Comment by ekazaev** [comment]
@max-potapov I see. Please let me know if I can help you

**Comment by max-potapov** [comment]
@ekazaev it's seems that this bug is related to SPM and we don't need to fix it because we use this library only in main app and not in extensions. Here is a link: https://bugs.swift.org/browse/SR-14944

**Comment by ekazaev** [comment]
@max-potapov Oh crap. Sorry about that. May be some temporary workaround is needed?

**Comment by max-potapov** [comment]
> @max-potapov Oh crap. Sorry about that. May be some temporary workaround is needed?

I would suggest to wait next Tuesday may be beta 4 will be available

**Comment by max-potapov** [comment]
Didn't check the latest beta but workaround is to use CocoaPods instead of SPM. Maybe this hint can help someone :)

**Comment by ekazaev** [comment]
@max-potapov thank you. Classic apple

**Pull request closed without merging**
